import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import { SideBar } from "./_component/SideBar";
import { Flex } from "antd";
import StyledComponentsRegistry from "@/lib/registry";
import RQProvider from "./_component/RQProvider";
import "./globals.css";

const inter = Noto_Sans_KR({ weight: ['500'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: 'flex', margin: 0 }}>
        <RQProvider>
          <StyledComponentsRegistry>
            <SideBar></SideBar>
            <Flex gap={'middle'} align="start" vertical style={{ width: '84vw', padding: '20px' }}>
              {children}
            </Flex>
          </StyledComponentsRegistry>
        </RQProvider>


      </body>
    </html>
  );
}
