import type { Metadata } from 'next';
import { Flex } from 'antd';
import RQProvider from './_component/RQProvider';
import './globals.css';
import PageTransition from '@/components/Upload/PageTranstion/PageTransition';
import DefaultLayout from '@/layout/Default/DefaultLayout';
import LoadingSpinner from '@/components/Loading/Spinner/LoadingSpinner';
import RouteChangeHandler from '@/components/RouteChangeHandler';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google AdSense 스크립트 */}
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7115543754190550"
          crossOrigin="anonymous"
        />
      </head>
      <body >
        <RQProvider>
          <PageTransition>
            <Flex vertical style={{ width: '100%' }}>
              <LoadingSpinner />
              <RouteChangeHandler />
              <DefaultLayout >{children}</DefaultLayout>

            </Flex>
          </PageTransition>

        </RQProvider>
      </body>
    </html>
  );
}
